export const pokemonTypeColorScheme = {
  normal: { bg: "bg-zinc-400", text: "text-zinc-800" },
  fire: { bg: "bg-orange-500", text: "text-white" },
  water: { bg: "bg-blue-500", text: "text-white" },
  electric: { bg: "bg-yellow-400", text: "text-gray-800" },
  grass: { bg: "bg-green-500", text: "text-white" },
  ice: { bg: "bg-teal-200", text: "text-teal-800" },
  fighting: { bg: "bg-red-600", text: "text-white" },
  poison: { bg: "bg-purple-500", text: "text-white" },
  ground: { bg: "bg-yellow-600", text: "text-white" },
  flying: { bg: "bg-indigo-300", text: "text-indigo-800" },
  psychic: { bg: "bg-pink-400", text: "text-white" },
  bug: { bg: "bg-yellow-600", text: "text-gray-800" },
  rock: { bg: "bg-yellow-800", text: "text-white" },
  ghost: { bg: "bg-indigo-800", text: "text-white" },
  dragon: { bg: "bg-purple-700", text: "text-white" },
  dark: { bg: "bg-gray-600", text: "text-white" },
  steel: { bg: "bg-gray-300", text: "text-gray-800" },
  dark2: { bg: "bg-pink-300", text: "text-gray-800" },
  fairy: { bg: "bg-rose-300", text: "text-white" },
};
